name: uikit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #    core
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.0.1
  provider: ^6.0.3
  get_it: ^7.2.0
  rxdart:
  dio: ^4.0.6
  http: ^0.13.5
  nil: ^1.1.1
  url_launcher: ^6.1.6
  intl: ^0.17.0




  #ui
  flutter_screenutil: ^5.0.1
  lottie: ^1.3.0
  cupertino_icons: ^1.0.2
  flutter_svg:
  animate_do: ^2.1.0
  modal_bottom_sheet: ^2.0.1
  focus_detector: ^2.0.1
  sensors_plus: ^1.3.2
  keyboard_attachable: ^2.1.0
  animations:
  cached_network_image: ^3.2.1
  photo_view: ^0.14.0
  custom_pop_up_menu: ^1.2.4
  expandable: ^5.0.1
  flutter_slidable: ^2.0.0
#  map
  google_maps_flutter: ^2.2.0
  map_picker: ^0.0.3
  geocoding: ^2.0.5
#  location: ^4.4.0
#  geolocator: ^9.0.2
  permission_handler: ^10.0.1
#  geocoding: ^2.0.5
#  map_location_picker: ^1.0.2
  #firebase
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  firebase_messaging: ^14.0.3

  #device info and permissions
  device_info_plus: ^8.0.0


  #helper
  pin_code_fields: ^7.4.0



  #test:
  equatable:
#  uikit:
#    git:
#      url: https://github.com/sohrabonline/uikit/module/uikit.git
#      ref: soh # branch name




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  logger: ^1.1.0




flutter:


  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/anim/

  fonts:
    - family: SF Pro Display Semibold
      fonts:
        - asset: assets/fonts/sfprosemibold.ttf
          style: normal
          weight: 400
    - family: sf
      fonts:
        - asset: assets/fonts/sf.ttf
          style: normal
          weight: 400
